jobs:
  build:
    docker:
      - image: "cimg/ruby:3.2.1-browsers"
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: "cimg/ruby:3.2.1-browsers"
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
  browser-tools: circleci/browser-tools@1.4.1
workflows:
  build_and_checking:
    jobs:
      - build
      - checking
