jobs:
  build:
    docker:
      - image: "cimg/ruby:3.2.1-browsers"
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: "cimg/ruby:3.2.1-browsers"
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: "cimg/ruby:3.2.1-browsers"
      - image: "cimg/redis:7.0.8"
      - image: "circleci/mongo:4.4.3"
    environment:
      PAGER: cat
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: "dockerize -wait tcp://localhost:27017 -timeout 1m"
          name: Wait for DB
      - run: sudo apt-get update && sudo apt install -y imagemagick
      - browser-tools/install-browser-tools
      - run:
          command: "curl -LO http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb && sudo dpkg -i libffi6_3.2.1-8_amd64.deb"
          name: "Install libffi6 for backwards-compatibility"
      - ruby/rspec-test

version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
  browser-tools: circleci/browser-tools@1.4.1
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
